### ISSUE TITLE
What's your gn flags to compile Webrtc ?

### ISSUE THREAD

**Issue by PunitSalian** [llamerada-jp/webrtc-cpp-sample#16]
Hi, I am using g++ to compile an application with your webrtc build, but I get these warnings. Can you tell me what I might be doing wrong ?
 local/include/api/transport/network_control.h:84:30: warning: attribute ignored [-Wattributes]
       ABSL_MUST_USE_RESULT = 0;

**Comment by llamerada-jp** [comment]
Hi @PunitSalian
The detailed build options are generated by `cmake`, so I recommend you using verbose options to get it.
Please change the build script like `make VERBOSE=1` at the below position.
https://github.com/llamerada-jp/webrtc-cpp-sample/blob/master/build.sh#L68

Messages caused by `ABSL_MUST_USE_RESULT` are output in my environment too. 
It seems to be trying to warn you if return values are not used in the library (ABSL).
But this macro is not run well. It seems no harm in it, so I ignore it. I agree that it's confusing.

**Comment by PunitSalian** [comment]
Thanks
